# Generated by Django 5.1 on 2024-08-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='body',
            field=models.CharField(max_length=200),
        ),
    ]
