# Generated by Django 5.1 on 2024-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_login_delete_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=100),
            preserve_default=False,
        ),
    ]
